---
- name: install a kubernetes
  hosts: localhost
  tasks:
  - name: get k8s variant
    set_fact:
      k8s: "{{ lookup('ansible.builtin.env', 'K8S') | default('k3s', True) }}"
  - name: run k8s variant
    ansible.builtin.include_tasks: "{{ k8s }}/up.yml"
  - name: Add ingress-nginx chart repo
    kubernetes.core.helm_repository:
      name: ingress-nginx
      repo_url: "https://kubernetes.github.io/ingress-nginx"
  - name: Deploy latest version of ingress-nginx
    kubernetes.core.helm:
      name: ingress-nginx
      chart_ref: ingress-nginx/ingress-nginx
      release_namespace: default
